### ISSUE TITLE
怎么识别中文图片，文本截图

### ISSUE THREAD

**Issue by BigBigDeBoy** [LZ9/Conjurer#1]

**Comment by LZ9** [comment]
@BigBigDeBoy 你好，可以参考demo里的图片识别方法：https://github.com/LZ9/Conjurer/blob/master/app/src/main/java/com/lodz/android/conjurerdemo/MainActivity.kt#L187
PS：请参考使用教程，先将语言包放入：
https://github.com/LZ9/Conjurer#3%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B
